import { TargetLanguage } from "../../types";
import { VocabChapter, GrammarChapter } from "./types";

export const VOCABULARY_CHAPTERS: Record<TargetLanguage, VocabChapter[]> = {
  English: [
    {
      id: "en-vocab-ch1",
      chapterNumber: 1,
      title: "Everyday Essentials & Social Introductions",
      subtitle: "High-frequency foundation vocabulary for instant conversational confidence",
      cefrLevel: "A1",
      badge: "Essential Core",
      category: "Daily Life",
      iconName: "Sparkles",
      summary: "Master the words that make up 60% of spoken English interactions: polite greetings, personal introductions, numbers, and survival inquiries.",
      words: [
        {
          id: "w-en-1",
          word: "Pleasure",
          ipa: "/ˈpleʒ.ər/",
          meaning: "A feeling of happy satisfaction or a polite formula when meeting someone",
          partOfSpeech: "noun",
          exampleSentence: "It is an absolute pleasure to finally meet you in person.",
          exampleTranslation: "Es un placer absoluto conocerte finalmente en persona.",
          collocations: ["My pleasure", "With pleasure", "Great pleasure"],
        },
        {
          id: "w-en-2",
          word: "Appreciate",
          ipa: "/əˈpriː.ʃi.eɪt/",
          meaning: "To recognize the full worth of something or express sincere gratitude",
          partOfSpeech: "verb",
          exampleSentence: "I truly appreciate your patience while I practice my speaking.",
          exampleTranslation: "Aprecio de verdad tu paciencia mientras practico mi pronunciación.",
          collocations: ["Appreciate your help", "Deeply appreciate", "Highly appreciate"],
        },
        {
          id: "w-en-3",
          word: "Recommend",
          ipa: "/ˌrek.əˈmend/",
          meaning: "To suggest something as being good, suitable, or advisable for a purpose",
          partOfSpeech: "verb",
          exampleSentence: "Could you recommend a quiet spot nearby where I can study?",
          exampleTranslation: "¿Podrías recomendarme un lugar tranquilo cerca donde pueda estudiar?",
          collocations: ["Highly recommend", "Recommend trying", "Recommend against"],
        },
        {
          id: "w-en-4",
          word: "Available",
          ipa: "/əˈveɪ.lə.bəl/",
          meaning: "Able to be used, obtained, or free to do something / meet",
          partOfSpeech: "adjective",
          exampleSentence: "Are you available for a quick five-minute coffee chat this afternoon?",
          exampleTranslation: "¿Estás disponible para una rápida charla de café esta tarde?",
          collocations: ["Readily available", "Available for", "Make available"],
        },
        {
          id: "w-en-5",
          word: "Fortunately",
          ipa: "/ˈfɔːr.tʃən.ət.li/",
          meaning: "Happening by good luck; luckily",
          partOfSpeech: "adverb",
          exampleSentence: "Fortunately, the train arrived right on schedule despite the heavy rain.",
          exampleTranslation: "Afortunadamente, el tren llegó justo a tiempo a pesar de la fuerte lluvia.",
          collocations: ["Fortunately for us", "Most fortunately"],
        },
        {
          id: "w-en-6",
          word: "Catch up",
          ipa: "/kætʃ ʌp/",
          meaning: "To talk to someone you have not seen recently and hear their latest news",
          partOfSpeech: "phrase",
          exampleSentence: "It has been far too long! We definitely need to catch up soon.",
          exampleTranslation: "¡Ha pasado demasiado tiempo! Sin duda tenemos que ponernos al día pronto.",
          collocations: ["Catch up on news", "Catch up with friends", "Play catch-up"],
        },
      ],
      quizQuestions: [
        {
          id: "q-en-v1-1",
          question: "Which word best completes: 'Could you ______ a good restaurant in this neighborhood?'",
          options: ["recommend", "appreciate", "pleasure", "catch up"],
          correctIndex: 0,
          explanation: "'Recommend' means to suggest something favorable to someone.",
        },
        {
          id: "q-en-v1-2",
          question: "When someone says 'Thank you so much for your assistance!', a natural polite response is:",
          options: ["It's my pleasure!", "I am available.", "Fortunately!", "Catch up!"],
          correctIndex: 0,
          explanation: "'It's my pleasure' is a warm, gracious alternative to 'You're welcome'.",
        },
        {
          id: "q-en-v1-3",
          question: "What does the phrasal verb 'catch up' mean in casual conversation?",
          options: [
            "To talk with an acquaintance to hear what has been happening in their life",
            "To physically chase someone down the street",
            "To grab something that is falling from a table",
            "To cancel a scheduled meeting",
          ],
          correctIndex: 0,
          explanation: "In conversation, 'catch up' means sharing updates after not seeing each other for a while.",
        },
      ],
    },
    {
      id: "en-vocab-ch2",
      chapterNumber: 2,
      title: "Daily Routines, Home & Wellbeing",
      subtitle: "Vocabulary for habits, productivity, domestic living, and emotional balance",
      cefrLevel: "A2",
      badge: "Daily Fluency",
      category: "Lifestyle",
      iconName: "Clock",
      summary: "Describe your morning rituals, chores, hobbies, and personal boundaries with clarity and natural collocations.",
      words: [
        {
          id: "w-en-7",
          word: "Consistent",
          ipa: "/kənˈsɪs.tənt/",
          meaning: "Acting or done in the same way over time, especially to be fair or accurate",
          partOfSpeech: "adjective",
          exampleSentence: "Consistent daily practice is the true secret to language mastery.",
          exampleTranslation: "La práctica diaria constante es el verdadero secreto del dominio del idioma.",
          collocations: ["Consistent effort", "Stay consistent", "Remarkably consistent"],
        },
        {
          id: "w-en-8",
          word: "Unwind",
          ipa: "/ʌnˈwaɪnd/",
          meaning: "To relax after a period of work or tension",
          partOfSpeech: "verb",
          exampleSentence: "After a hectic day at the office, I like to unwind with a cup of herbal tea.",
          exampleTranslation: "Después de un día ajetreado en la oficina, me gusta relajarme con un té.",
          collocations: ["Unwind after work", "Time to unwind", "Help unwind"],
        },
        {
          id: "w-en-9",
          word: "Prioritize",
          ipa: "/praɪˈɔːr.ə.taɪz/",
          meaning: "To designate or treat something as more important than other things",
          partOfSpeech: "verb",
          exampleSentence: "I always prioritize my morning workout before checking work emails.",
          exampleTranslation: "Siempre doy prioridad a mi entrenamiento matutino antes de revisar correos.",
          collocations: ["Prioritize tasks", "Learn to prioritize", "Carefully prioritize"],
        },
        {
          id: "w-en-10",
          word: "Convenient",
          ipa: "/kənˈviː.ni.ənt/",
          meaning: "Fitting in well with a person's needs, activities, and plans; easy to reach",
          partOfSpeech: "adjective",
          exampleSentence: "Having a grocery store right around the corner is extraordinarily convenient.",
          exampleTranslation: "Tener una tienda de comestibles justo a la vuelta es extraordinariamente conveniente.",
          collocations: ["Convenient location", "Extremely convenient", "At a convenient time"],
        },
        {
          id: "w-en-11",
          word: "Routine",
          ipa: "/ruːˈtiːn/",
          meaning: "A sequence of actions regularly followed; a fixed program",
          partOfSpeech: "noun",
          exampleSentence: "Establishing an evening reading routine dramatically improved my sleep.",
          exampleTranslation: "Establecer una rutina de lectura nocturna mejoró drásticamente mi sueño.",
          collocations: ["Daily routine", "Break the routine", "Establish a routine"],
        },
        {
          id: "w-en-12",
          word: "Recharge",
          ipa: "/riːˈtʃɑːrdʒ/",
          meaning: "To regain energy, focus, or enthusiasm through rest or leisure",
          partOfSpeech: "verb",
          exampleSentence: "A weekend hiking trip in the mountains gave me the space to recharge.",
          exampleTranslation: "Un viaje de senderismo de fin de semana en las montañas me dio espacio para recargar energías.",
          collocations: ["Recharge my batteries", "Need to recharge", "Full recharge"],
        },
      ],
      quizQuestions: [
        {
          id: "q-en-v2-1",
          question: "Which word means 'to relax and let go of stress after a busy workday'?",
          options: ["unwind", "prioritize", "routine", "consistent"],
          correctIndex: 0,
          explanation: "'Unwind' specifically describes releasing tension and resting.",
        },
        {
          id: "q-en-v2-2",
          question: "What is the best adjective for an apartment that is 2 minutes from the subway station?",
          options: ["convenient", "consistent", "recharge", "routine"],
          correctIndex: 0,
          explanation: "'Convenient' describes something that saves effort and fits needs effortlessly.",
        },
      ],
    },
    {
      id: "en-vocab-ch3",
      chapterNumber: 3,
      title: "City Navigation, Travel & Culinary Exploration",
      subtitle: "Transit logistics, airports, hospitality, and asking like a seasoned traveler",
      cefrLevel: "A2",
      badge: "World Voyager",
      category: "Travel",
      iconName: "Compass",
      summary: "Confidently explore foreign cities, handle ticket counters, communicate dietary preferences, and resolve hotel delays.",
      words: [
        {
          id: "w-en-13",
          word: "Departure",
          ipa: "/dɪˈpɑːr.tʃər/",
          meaning: "The action of leaving, especially to start a journey; scheduled flight/train exit",
          partOfSpeech: "noun",
          exampleSentence: "Passengers are requested to proceed to departure gate 24 immediately.",
          exampleTranslation: "Se solicita a los pasajeros que se dirijan de inmediato a la puerta de salida 24.",
          collocations: ["Departure lounge", "Time of departure", "Scheduled departure"],
        },
        {
          id: "w-en-14",
          word: "Itinerary",
          ipa: "/aɪˈtɪn.ə.rer.i/",
          meaning: "A planned route, schedule, or list of places to visit on a journey",
          partOfSpeech: "noun",
          exampleSentence: "Our travel itinerary includes two days in Kyoto followed by a weekend in Osaka.",
          exampleTranslation: "Nuestro itinerario de viaje incluye dos días en Kioto seguidos de un fin de semana en Osaka.",
          collocations: ["Detailed itinerary", "Change the itinerary", "Travel itinerary"],
        },
        {
          id: "w-en-15",
          word: "Accommodation",
          ipa: "/əˌkɑː.məˈdeɪ.ʃən/",
          meaning: "A room, group of rooms, or building in which someone may live or stay",
          partOfSpeech: "noun",
          exampleSentence: "We booked boutique hotel accommodation right in the historic city center.",
          exampleTranslation: "Reservamos alojamiento en un hotel boutique justo en el centro histórico.",
          collocations: ["Book accommodation", "Luxury accommodation", "Budget accommodation"],
        },
        {
          id: "w-en-16",
          word: "Commute",
          ipa: "/kəˈmjuːt/",
          meaning: "To travel some distance between one's home and place of work on a regular basis",
          partOfSpeech: "verb",
          exampleSentence: "Many professionals commute by electric bicycle rather than driving.",
          exampleTranslation: "Muchos profesionales viajan al trabajo en bicicleta eléctrica en lugar de conducir.",
          collocations: ["Daily commute", "Commute to work", "Long commute"],
        },
        {
          id: "w-en-17",
          word: "Breathtaking",
          ipa: "/ˈbreθˌteɪ.kɪŋ/",
          meaning: "Astonishing or awe-inspiring in quality, beauty, or scale",
          partOfSpeech: "adjective",
          exampleSentence: "The summit offered a breathtaking panoramic view of the misty valley below.",
          exampleTranslation: "La cumbre ofrecía una vista panorámica impresionante del valle brumoso debajo.",
          collocations: ["Breathtaking view", "Breathtaking scenery", "Truly breathtaking"],
        },
      ],
      quizQuestions: [
        {
          id: "q-en-v3-1",
          question: "What do you call the document or plan that details where you will travel every day?",
          options: ["Itinerary", "Commute", "Departure", "Accommodation"],
          correctIndex: 0,
          explanation: "An 'itinerary' is a detailed schedule or list of travel stops.",
        },
      ],
    },
    {
      id: "en-vocab-ch4",
      chapterNumber: 4,
      title: "Workplace, Business & Tech Communication",
      subtitle: "Professional vocabulary for meetings, strategic proposals, and digital collaboration",
      cefrLevel: "B1",
      badge: "Executive Pro",
      category: "Career",
      iconName: "Briefcase",
      summary: "Sound persuasive, diplomatic, and articulate in international business environments, client pitches, and team retrospectives.",
      words: [
        {
          id: "w-en-18",
          word: "Collaborate",
          ipa: "/kəˈlæb.ə.reɪt/",
          meaning: "To work jointly on an activity or project to create or produce something",
          partOfSpeech: "verb",
          exampleSentence: "Our product designers collaborate closely with software engineers from day one.",
          exampleTranslation: "Nuestros diseñadores de producto colaboran estrechamente con ingenieros desde el primer día.",
          collocations: ["Collaborate closely", "Collaborate on a project", "Collaborative effort"],
        },
        {
          id: "w-en-19",
          word: "Milestone",
          ipa: "/ˈmaɪl.stoʊn/",
          meaning: "An action or event marking a significant stage in development or project delivery",
          partOfSpeech: "noun",
          exampleSentence: "Reaching one million active users was a monumental milestone for the startup.",
          exampleTranslation: "Alcanzar un millón de usuarios activos fue un hito monumental para la startup.",
          collocations: ["Reach a milestone", "Key milestone", "Major milestone"],
        },
        {
          id: "w-en-20",
          word: "Feasible",
          ipa: "/ˈfiː.zə.bəl/",
          meaning: "Possible to do easily or conveniently; realistic within constraints",
          partOfSpeech: "adjective",
          exampleSentence: "Given our current engineering bandwidth, launching next month is entirely feasible.",
          exampleTranslation: "Dada nuestra capacidad de ingeniería actual, lanzar el próximo mes es completamente factible.",
          collocations: ["Economically feasible", "Technically feasible", "Feasible solution"],
        },
        {
          id: "w-en-21",
          word: "Streamline",
          ipa: "/ˈstriːm.laɪn/",
          meaning: "To make an organization or system more efficient by employing faster or simpler methods",
          partOfSpeech: "verb",
          exampleSentence: "The new automation pipeline helped streamline our weekly reporting workflow.",
          exampleTranslation: "El nuevo flujo de automatización ayudó a optimizar nuestro informe semanal.",
          collocations: ["Streamline processes", "Streamline operations", "Streamline workflow"],
        },
        {
          id: "w-en-22",
          word: "Leverage",
          ipa: "/ˈlev.ər.ɪdʒ/",
          meaning: "To use something to maximum advantage to achieve a target outcome",
          partOfSpeech: "verb",
          exampleSentence: "We can leverage our proprietary dataset to train more accurate AI models.",
          exampleTranslation: "Podemos aprovechar nuestro conjunto de datos propietario para entrenar modelos de IA más precisos.",
          collocations: ["Leverage technology", "Leverage assets", "Gain leverage"],
        },
        {
          id: "w-en-23",
          word: "Proactive",
          ipa: "/proʊˈæk.tɪv/",
          meaning: "Creating or controlling a situation rather than just responding to it after it happens",
          partOfSpeech: "adjective",
          exampleSentence: "Taking a proactive approach to security prevents vulnerabilities before release.",
          exampleTranslation: "Adoptar un enfoque proactivo de seguridad evita vulnerabilidades antes del lanzamiento.",
          collocations: ["Proactive approach", "Proactive measures", "Be proactive"],
        },
      ],
      quizQuestions: [
        {
          id: "q-en-v4-1",
          question: "When a project proposal is realistic, achievable, and practical, we say it is:",
          options: ["Feasible", "Proactive", "Milestone", "Streamline"],
          correctIndex: 0,
          explanation: "'Feasible' means capable of being done successfully within realistic limits.",
        },
        {
          id: "q-en-v4-2",
          question: "What verb means 'to optimize or simplify a workflow to remove unnecessary steps'?",
          options: ["Streamline", "Leverage", "Collaborate", "Milestone"],
          correctIndex: 0,
          explanation: "'Streamline' means refining a process to make it faster and smoother.",
        },
      ],
    },
    {
      id: "en-vocab-ch5",
      chapterNumber: 5,
      title: "Nuance, Emotion & Powerful Idiomatic Expressions",
      subtitle: "Express subtle human feelings, metaphors, and native colloquial speech",
      cefrLevel: "B2",
      badge: "Fluent Expressionist",
      category: "Idioms & Nuance",
      iconName: "Brain",
      summary: "Go beyond literal words. Learn figurative phrasing, emotional subtleties, and conversational color that native speakers use intuitively.",
      words: [
        {
          id: "w-en-24",
          word: "Bite the bullet",
          ipa: "/baɪt ðə ˈbʊl.ɪt/",
          meaning: "To face a difficult or unpleasant situation with courage and resolve",
          partOfSpeech: "idiom",
          exampleSentence: "I dreaded having the tough salary negotiation, but I finally bit the bullet.",
          exampleTranslation: "Temía tener la difícil negociación salarial, pero finalmente apreté los dientes y lo afronté.",
          collocations: ["Decide to bite the bullet", "Time to bite the bullet"],
        },
        {
          id: "w-en-25",
          word: "See eye to eye",
          ipa: "/siː aɪ tuː aɪ/",
          meaning: "To be in complete agreement with someone on a topic or policy",
          partOfSpeech: "idiom",
          exampleSentence: "Although they respect each other, the two partners rarely see eye to eye on marketing.",
          exampleTranslation: "Aunque se respetan, los dos socios rara vez están de acuerdo en marketing.",
          collocations: ["Don't see eye to eye", "See eye to eye on everything"],
        },
        {
          id: "w-en-26",
          word: "Ambivalent",
          ipa: "/æmˈbɪv.ə.lənt/",
          meaning: "Having mixed feelings or contradictory ideas about something or someone",
          partOfSpeech: "adjective",
          exampleSentence: "He felt ambivalent about moving abroad: excited for adventure yet sad to leave home.",
          exampleTranslation: "Se sentía indeciso sobre mudarse al extranjero: emocionado por la aventura pero triste por partir.",
          collocations: ["Feel ambivalent", "Ambivalent attitude", "Deeply ambivalent"],
        },
        {
          id: "w-en-27",
          word: "Resilient",
          ipa: "/rɪˈzɪl.jənt/",
          meaning: "Able to withstand or recover quickly from difficult conditions or setbacks",
          partOfSpeech: "adjective",
          exampleSentence: "Children are often remarkably resilient when adapting to new languages.",
          exampleTranslation: "Los niños suelen ser notablemente resilientes al adaptarse a nuevos idiomas.",
          collocations: ["Highly resilient", "Resilient spirit", "Emotionally resilient"],
        },
        {
          id: "w-en-28",
          word: "Blessing in disguise",
          ipa: "/ˈbles.ɪŋ ɪn dɪsˈɡaɪz/",
          meaning: "An apparent misfortune that eventually results in good or beneficial outcomes",
          partOfSpeech: "idiom",
          exampleSentence: "Losing that job was a blessing in disguise; it inspired me to found my own business.",
          exampleTranslation: "Perder ese trabajo fue una bendición disfrazada; me inspiró a fundar mi propia empresa.",
          collocations: ["Turned out to be a blessing in disguise", "Real blessing in disguise"],
        },
      ],
      quizQuestions: [
        {
          id: "q-en-v5-1",
          question: "If two colleagues agree completely on an issue, you can say they:",
          options: ["See eye to eye", "Bite the bullet", "Feel ambivalent", "Blessing in disguise"],
          correctIndex: 0,
          explanation: "'See eye to eye' means to have harmonious, matching views on a subject.",
        },
      ],
    },
    {
      id: "en-vocab-ch6",
      chapterNumber: 6,
      title: "Global Society, Innovation & Critical Thinking",
      subtitle: "Elevate your vocabulary for podcasts, debates, academic writing, and current affairs",
      cefrLevel: "C1",
      badge: "Master Debater",
      category: "Academic",
      iconName: "GraduationCap",
      summary: "Engage in intellectual discourse on ethics, artificial intelligence, sustainability, and international philosophy.",
      words: [
        {
          id: "w-en-29",
          word: "Ubiquitous",
          ipa: "/juːˈbɪk.wə.təs/",
          meaning: "Present, appearing, or found everywhere simultaneously",
          partOfSpeech: "adjective",
          exampleSentence: "Smartphones have transitioned from luxury novelties to ubiquitous necessities.",
          exampleTranslation: "Los teléfonos inteligentes han pasado de novedades de lujo a necesidades omnipresentes.",
          collocations: ["Ubiquitous presence", "Become ubiquitous", "Virtually ubiquitous"],
        },
        {
          id: "w-en-30",
          word: "Paradigm",
          ipa: "/ˈpær.ə.daɪm/",
          meaning: "A typical pattern or model of something; an overarching conceptual framework",
          partOfSpeech: "noun",
          exampleSentence: "Generative artificial intelligence represents a historic paradigm shift in education.",
          exampleTranslation: "La inteligencia artificial generativa representa un cambio de paradigma histórico en la educación.",
          collocations: ["Paradigm shift", "New paradigm", "Prevailing paradigm"],
        },
        {
          id: "w-en-31",
          word: "Articulate",
          ipa: "/ɑːrˈtɪk.jə.lət/",
          meaning: "Having or showing the ability to speak fluently and coherently; express ideas clearly",
          partOfSpeech: "adjective",
          exampleSentence: "She presented an articulate defense of sustainable urban public transport.",
          exampleTranslation: "Presentó una defensa elocuente del transporte público urbano sostenible.",
          collocations: ["Highly articulate", "Articulate speaker", "Articulate argument"],
        },
        {
          id: "w-en-32",
          word: "Catalyst",
          ipa: "/ˈkæt̬.əl.ɪst/",
          meaning: "A person or thing that precipitates an event or rapid transformation",
          partOfSpeech: "noun",
          exampleSentence: "The new community language center served as a catalyst for local cultural exchange.",
          exampleTranslation: "El nuevo centro comunitario de idiomas sirvió como catalizador para el intercambio cultural local.",
          collocations: ["Act as a catalyst", "Major catalyst", "Catalyst for change"],
        },
      ],
      quizQuestions: [
        {
          id: "q-en-v6-1",
          question: "When a concept or technology is found everywhere across society, it is described as:",
          options: ["Ubiquitous", "Articulate", "Paradigm", "Catalyst"],
          correctIndex: 0,
          explanation: "'Ubiquitous' means existing or being encountered everywhere.",
        },
      ],
    },
  ],
  Spanish: [
    {
      id: "es-vocab-ch1",
      chapterNumber: 1,
      title: "Esenciales y Primeras Conversaciones",
      subtitle: "Vocabulario clave para saludar, presentarte y la vida cotidiana",
      cefrLevel: "A1",
      badge: "Núcleo Básico",
      category: "Vida Cotidiana",
      iconName: "Sparkles",
      summary: "Aprende los términos más frecuentes para desenvolverte con naturalidad desde tu primera charla en español.",
      words: [
        {
          id: "w-es-1",
          word: "Mucho gusto",
          ipa: "[ˈmu.tʃo ˈɣus.to]",
          meaning: "Pleased / Nice to meet you",
          partOfSpeech: "phrase",
          exampleSentence: "Hola, me llamo Sofía. ¡Mucho gusto!",
          exampleTranslation: "Hello, my name is Sofia. Nice to meet you!",
        },
        {
          id: "w-es-2",
          word: "Disculpe",
          ipa: "[disˈkul.pe]",
          meaning: "Excuse me / Pardon (formal polite)",
          partOfSpeech: "phrase",
          exampleSentence: "Disculpe, ¿sabe dónde queda la estación de tren?",
          exampleTranslation: "Excuse me, do you know where the train station is?",
        },
      ],
      quizQuestions: [
        {
          id: "q-es-v1",
          question: "¿Qué dices educadamente cuando conoces a alguien por primera vez?",
          options: ["¡Mucho gusto!", "¡Disculpe!", "¿Cuánto cuesta?", "Hasta luego"],
          correctIndex: 0,
          explanation: "'Mucho gusto' es la fórmula más común de cortesía.",
        },
      ],
    },
  ],
  French: [
    {
      id: "fr-vocab-ch1",
      chapterNumber: 1,
      title: "Les Essentiels de la Conversation",
      subtitle: "Salutations, formules de politesse et vie de tous les jours",
      cefrLevel: "A1",
      badge: "Fondations",
      category: "Quotidien",
      iconName: "Sparkles",
      summary: "Les mots indispensables pour commander, saluer et se présenter en français.",
      words: [
        {
          id: "w-fr-1",
          word: "Enchanté(e)",
          ipa: "[ɑ̃.ʃɑ̃.te]",
          meaning: "Delighted / Nice to meet you",
          partOfSpeech: "phrase",
          exampleSentence: "Bonjour, je m'appelle Julien. Enchanté !",
          exampleTranslation: "Hello, my name is Julien. Nice to meet you!",
        },
      ],
      quizQuestions: [
        {
          id: "q-fr-v1",
          question: "Quelle expression utilise-t-on pour saluer chaleureusement lors d'une première rencontre ?",
          options: ["Enchanté !", "S'il vous plaît", "Au revoir", "De rien"],
          correctIndex: 0,
          explanation: "'Enchanté' signifie ravi de faire votre connaissance.",
        },
      ],
    },
  ],
  German: [],
  Japanese: [],
  Mandarin: [],
};

export const GRAMMAR_CHAPTERS: Record<TargetLanguage, GrammarChapter[]> = {
  English: [
    {
      id: "en-gram-ch1",
      chapterNumber: 1,
      title: "Sentence Architecture & Core Parts of Speech",
      subtitle: "The infallible Subject-Verb-Object formula and article mastery",
      cefrLevel: "A1",
      badge: "Architect",
      summary: "English is a strictly word-ordered language. Discover how S-V-O (Subject + Verb + Object) creates effortless clarity, and master when to use 'a', 'an', or 'the'.",
      formula: "Subject + Verb + (Object / Complement) [+ Manner + Place + Time]",
      deepExplanation:
        "Unlike inflected languages where word endings convey grammatical roles, English depends on rigid positional syntax. The subject almost always precedes the finite verb in affirmative statements. Adjectives precede nouns ('a quiet room', not 'a room quiet'). When indicating time and location at the end of a clause, follow the natural sequence: How (Manner) -> Where (Place) -> When (Time).",
      keyRules: [
        "Definite Article 'The': Use when both speaker and listener know the specific item, or when there is only one in the context.",
        "Indefinite Article 'A / An': Use 'a' before consonant sounds (a university, a book) and 'an' before vowel sounds (an hour, an apple).",
        "Third-Person Singular: In the Present Simple, verbs taking he/she/it must append -s or -es (e.g., 'He speaks', 'She watches').",
      ],
      commonPitfalls: [
        "Saying 'I have 25 years' instead of 'I am 25 years old' (English expresses age with the state-of-being verb 'to be').",
        "Omitting the mandatory subject pronoun ('Is raining' is incorrect; English requires a dummy pronoun: 'It is raining').",
      ],
      examples: [
        {
          correct: "Elena plays the piano beautifully in her studio every evening.",
          incorrect: "Elena plays beautifully the piano every evening in her studio.",
          explanation: "Never place adverbs between a transitive verb ('plays') and its direct object ('the piano').",
        },
        {
          correct: "He lives in an old, historic apartment near the museum.",
          incorrect: "He lives in a old apartment near to museum.",
          explanation: "'Old' begins with a vowel sound, requiring 'an'. Definite reference to 'the museum' requires 'the'.",
        },
      ],
      practiceExercises: [
        {
          id: "ex-en-g1-1",
          question: "Choose the grammatically correct sentence order:",
          options: [
            "Marcus drank quickly the water.",
            "Marcus quickly drank the water.",
            "Drank Marcus quickly the water.",
            "Marcus drank the water quickly.",
          ],
          correctIndex: 1,
          explanation: "In English, do not separate a verb ('drank') from its direct object ('the water'). The adverb can precede the verb ('quickly drank') or conclude the clause ('drank the water quickly').",
        },
        {
          id: "ex-en-g1-2",
          question: "Fill in the blank: 'It takes ______ hour to drive to the airport.'",
          options: ["an", "a", "the", "one of"],
          correctIndex: 0,
          explanation: "Although 'hour' begins with the letter 'h', the 'h' is silent and produces an initial vowel sound /aʊər/, requiring 'an'.",
        },
      ],
      practicePrompt: "Explain your daily morning routine to Maestro using Subject + Verb + Object sentences, paying close attention to third-person -s and articles.",
    },
    {
      id: "en-gram-ch2",
      chapterNumber: 2,
      title: "The Timeline of Action: Simple vs. Continuous Tenses",
      subtitle: "Habits and general truths versus actions unfolding in the living moment",
      cefrLevel: "A2",
      badge: "Time Traveler",
      summary: "Understand the visual difference between the snapshot Present Simple (timeless, habitual) and the video Present Continuous (temporary, ongoing right now).",
      formula: "Present Simple: Subject + Base Verb(s) | Present Continuous: Subject + am/is/are + Verb-ing",
      deepExplanation:
        "The Present Simple is used for permanent facts ('The sun rises in the east'), routines ('I drink coffee at 8 AM'), and stative conditions ('I understand the concept'). In contrast, the Continuous aspect emphasizes that an action is incomplete, temporary, or actively happening right now. Be careful with 'stative verbs' (know, believe, love, seem) which rarely take continuous forms.",
      keyRules: [
        "Time Markers for Simple: always, usually, often, every day, rarely, never.",
        "Time Markers for Continuous: right now, at the moment, currently, this week, today.",
        "Stative Verbs: Verbs expressing mental states, emotions, or senses stay in the simple form (e.g., 'I want a coffee', NOT 'I am wanting a coffee').",
      ],
      commonPitfalls: [
        "Using Continuous for permanent habits: 'I am living in London' implies a temporary stay; 'I live in London' implies permanent residency.",
        "Forgetting the auxiliary 'be' in continuous: saying 'I studying' instead of 'I am studying'.",
      ],
      examples: [
        {
          correct: "I usually take the subway to work, but this week I am walking because the weather is lovely.",
          incorrect: "I am usually taking the subway to work, but this week I walk.",
          explanation: "'Usually' signals habit (Present Simple); 'this week' signals a temporary deviation (Present Continuous).",
        },
      ],
      practiceExercises: [
        {
          id: "ex-en-g2-1",
          question: "Which sentence correctly reflects an action in progress right now?",
          options: [
            "Listen! The teacher explains the rule.",
            "Listen! The teacher is explaining the rule.",
            "Listen! The teacher has explain the rule.",
            "Listen! The teacher explain the rule.",
          ],
          correctIndex: 1,
          explanation: "'Listen!' signals an event occurring at the exact moment of speech, requiring Present Continuous ('is explaining').",
        },
      ],
      practicePrompt: "Tell Maestro what you do for a living (habitual) and what you are actively learning right now (continuous).",
    },
    {
      id: "en-gram-ch3",
      chapterNumber: 3,
      title: "Connecting Past with Present: The Perfect Aspects",
      subtitle: "Mastering the Present Perfect (Have/Has + Past Participle) vs Past Simple",
      cefrLevel: "B1",
      badge: "Bridge Builder",
      summary: "The single greatest stumbling block for English learners decoded: why we use 'I have lived' vs 'I lived', and 'for' vs 'since'.",
      formula: "Present Perfect: Subject + have/has + Past Participle (V3)",
      deepExplanation:
        "The Past Simple isolates an action in a finished, closed historical time box ('yesterday', 'in 2019', 'last Tuesday'). The Present Perfect, however, builds a conceptual bridge between the past and the present moment: life experiences with no specific date ('I have visited Japan'), actions begun in the past that continue now ('I have worked here for three years'), and recent events with visible present consequences ('I have lost my keys—I can't open the door!').",
      keyRules: [
        "'Since' marks the specific starting point in time (since Monday, since 2018, since I graduated).",
        "'For' marks the duration or span of time (for five days, for three months, for an hour).",
        "Never use specific finished past timestamps (yesterday, two hours ago, in 1999) with the Present Perfect.",
      ],
      commonPitfalls: [
        "Saying 'I have seen that movie yesterday' (Wrong! 'Yesterday' requires Past Simple: 'I saw that movie yesterday').",
        "Mixing up 'for' and 'since': saying 'I have known him since two years' (Should be: 'for two years').",
      ],
      examples: [
        {
          correct: "I have lived in this city since 2021, and I absolutely love it.",
          incorrect: "I live in this city since 2021.",
          explanation: "Actions that began in the past and continue into the present require the Present Perfect in English.",
        },
      ],
      practiceExercises: [
        {
          id: "ex-en-g3-1",
          question: "Which sentence is grammatically flawless?",
          options: [
            "She has worked at the hospital for six years.",
            "She has worked at the hospital since six years.",
            "She worked at the hospital since 2020.",
            "She has worked at the hospital yesterday.",
          ],
          correctIndex: 0,
          explanation: "'For' precedes a duration ('six years'), and Present Perfect links that six-year span to today.",
        },
      ],
      practicePrompt: "Share three memorable life experiences you have had, and one thing you have been studying recently.",
    },
    {
      id: "en-gram-ch4",
      chapterNumber: 4,
      title: "Modals of Certainty, Obligation & Nuanced Politeness",
      subtitle: "Must, Should, Could, Might, and degrees of possibility",
      cefrLevel: "B1",
      badge: "Diplomat",
      summary: "Modals modulate the mood of a sentence from strict requirement ('must') to gentle recommendation ('should') and speculative deduction ('might').",
      formula: "Subject + Modal Verb + Base Verb (Infinitive without 'to')",
      deepExplanation:
        "Modal auxiliary verbs never change form (no '-s' in the third person, no '-ing', no '-ed'). They are immediately followed by the bare infinitive. When making deductions: 'It must be him' means 95% certainty; 'It could / may / might be him' means 50% possibility; 'It can't be him' means 99% impossibility.",
      keyRules: [
        "Obligation: 'Must' represents personal or urgent necessity; 'Have to' represents external rules or laws.",
        "Prohibition vs Lack of Obligation: 'You must not' means DO NOT DO IT (forbidden). 'You don't have to' means it is OPTIONAL.",
        "Past Deductions: Modal + have + past participle (e.g., 'He must have forgotten his umbrella').",
      ],
      commonPitfalls: [
        "Adding 'to' after modal verbs: saying 'I must to go' instead of 'I must go'.",
        "Confusing 'must not' (forbidden) with 'don't have to' (not necessary).",
      ],
      examples: [
        {
          correct: "You don't have to wear a suit to the dinner, but you should look tidy.",
          incorrect: "You must not to wear a suit...",
          explanation: "'Don't have to' shows it is voluntary. 'Must not' would mean suits are illegal or banned.",
        },
      ],
      practiceExercises: [
        {
          id: "ex-en-g4-1",
          question: "You see the lights off and no car in your neighbor's driveway. You deduce:",
          options: [
            "They must be away on vacation.",
            "They should to be away.",
            "They must not be at home necessarily.",
            "They can be on vacation surely.",
          ],
          correctIndex: 0,
          explanation: "'Must be' expresses strong positive deduction based on clear evidence.",
        },
      ],
      practicePrompt: "Give advice to someone preparing to visit your hometown using 'should', 'must', and 'could'.",
    },
    {
      id: "en-gram-ch5",
      chapterNumber: 5,
      title: "The Logic of 'If': Complete Conditional Structures",
      subtitle: "From scientific facts (Zero) to hypothetical fantasies (Second) and past regrets (Third)",
      cefrLevel: "B2",
      badge: "Strategist",
      summary: "Unlock the conditional calculus: learn how verb tenses shift one step into the past when speaking of hypotheticals.",
      formula: "Zero: If + present, present | First: If + present, will + verb | Second: If + past, would + verb | Third: If + had + V3, would have + V3",
      deepExplanation:
        "Conditionals describe causes and their consequences. In the First Conditional, we talk about real, plausible future outcomes ('If it rains, we will stay home'). In the Second Conditional, we step into the imagination or counterfactual present: we shift the verb into the past tense to create 'hypothetical distance' ('If I won the lottery, I would travel the globe'). In the Third Conditional, we evaluate past situations that cannot be altered ('If I had known, I would have helped').",
      keyRules: [
        "Never place 'will' or 'would' inside the 'if' condition clause (Say: 'If it rains...', NOT 'If it will rain...').",
        "In the Second Conditional, formal English uses 'were' for all subjects with the verb to be: 'If I were you...', 'If she were here...'.",
      ],
      commonPitfalls: [
        "Putting 'would' in the if-clause: saying 'If I would have more money...' instead of 'If I had more money...'.",
      ],
      examples: [
        {
          correct: "If I had more free time this weekend, I would gladly join your hiking trip.",
          incorrect: "If I would have more free time, I will join...",
          explanation: "The condition clause requires Past Simple ('had'), and the result clause requires 'would + verb'.",
        },
      ],
      practiceExercises: [
        {
          id: "ex-en-g5-1",
          question: "Complete the hypothetical sentence: 'If I ______ a superpower, I ______ the ability to fly.'",
          options: [
            "had / would choose",
            "have / will choose",
            "would have / chose",
            "had / will choose",
          ],
          correctIndex: 0,
          explanation: "Second Conditional for imaginary scenarios: If + past simple ('had'), result with would + base verb ('would choose').",
        },
      ],
      practicePrompt: "If you could master any three skills instantly tomorrow, what would you choose and why?",
    },
    {
      id: "en-gram-ch6",
      chapterNumber: 6,
      title: "Advanced Syntax: Passive Voice & Relative Clauses",
      subtitle: "Sophisticated sentence transformation for academic and executive writing",
      cefrLevel: "B2",
      badge: "Syntax Master",
      summary: "Transform active sentences into objective, authoritative passive phrasing, and combine complex thoughts with defining and non-defining relative clauses.",
      formula: "Passive: Subject + form of 'be' + Past Participle (V3) (+ by agent)",
      deepExplanation:
        "The passive voice shifts the spotlight from WHO performed an action to WHAT was affected or produced. It is widely used in journalism, scientific research, and professional reports when the agent is unknown, obvious, or less important than the result. Relative clauses (who, which, that, whose, where) eliminate choppy sentences by linking ideas seamlessly.",
      keyRules: [
        "Defining Relative Clauses: Essential to identity; no commas; can use 'that' or 'who'.",
        "Non-Defining Relative Clauses: Extra biographical info; bounded by commas; CANNOT use 'that' (must use 'which' or 'who').",
        "Passive Voice: Maintain the original sentence's tense in the auxiliary 'be' (e.g., 'is built', 'was built', 'has been built', 'will be built').",
      ],
      commonPitfalls: [
        "Using 'that' in non-defining clauses with commas (Wrong: 'My car, that is red, is fast.' Correct: 'My car, which is red, is fast.').",
      ],
      examples: [
        {
          correct: "The groundbreaking research was published by Dr. Martinez in the international journal.",
          incorrect: "The groundbreaking research published by Dr. Martinez...",
          explanation: "Passive requires the auxiliary verb 'was' + past participle 'published'.",
        },
      ],
      practiceExercises: [
        {
          id: "ex-en-g6-1",
          question: "Which sentence correctly uses a non-defining relative clause with proper punctuation?",
          options: [
            "My older brother, who lives in Toronto, works as an aerospace architect.",
            "My older brother that lives in Toronto, works as an aerospace architect.",
            "My older brother, that lives in Toronto works as an aerospace architect.",
            "My older brother which lives in Toronto, works as an aerospace architect.",
          ],
          correctIndex: 0,
          explanation: "Non-defining clauses about people require commas and the relative pronoun 'who' (never 'that' or 'which').",
        },
      ],
      practicePrompt: "Describe an impressive invention or historical monument using at least one passive sentence and one relative clause.",
    },
  ],
  Spanish: [
    {
      id: "es-gram-ch1",
      chapterNumber: 1,
      title: "Ser vs. Estar: La Distinción Esencial",
      subtitle: "Esencia permanente versus estado temporal y ubicación",
      cefrLevel: "A1",
      badge: "Fundamentos",
      summary: "Uno de los conceptos más fascinantes del español: cómo dos verbos distintos representan el verbo 'to be'.",
      formula: "Ser: Identidad, Origen, Cualidad | Estar: Ubicación, Estado de ánimo, Condición",
      deepExplanation: "Usa 'ser' para definir la naturaleza intrínseca de alguien o algo. Usa 'estar' para estados cambiantes y la ubicación física.",
      keyRules: [
        "Ser: Soy de Madrid (origen), Es médico (profesión), Es inteligente (rasgo permanente).",
        "Estar: Estoy cansado (estado), Está en casa (ubicación), La comida está caliente (condición).",
      ],
      commonPitfalls: [
        "Confundir 'es bueno' (cualidad moral/calidad) con 'está bueno' (delicioso o atractivo).",
      ],
      examples: [
        {
          correct: "La profesora es simpática, pero hoy está un poco enferma.",
          explanation: "'Es' para la personalidad; 'está' para su condición de salud hoy.",
        },
      ],
      practiceExercises: [
        {
          id: "ex-es-g1",
          question: "Completa: 'El café ______ delicioso hoy, pero la cafetería ______ en el centro.'",
          options: ["está / está", "es / es", "está / es", "es / está"],
          correctIndex: 0,
          explanation: "Condición de la comida ('está delicioso') y ubicación espacial ('está en el centro').",
        },
      ],
      practicePrompt: "Describe tu ciudad y cómo te sientes hoy usando los verbos ser y estar.",
    },
  ],
  French: [],
  German: [],
  Japanese: [],
  Mandarin: [],
};
